import { Inter, Edu_VIC_WA_NT_Beginner } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Menu from "@/compoment/menu/Menu";

const inter = Inter({ subsets: ["latin"] });

const eduVIC = Edu_VIC_WA_NT_Beginner({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={eduVIC.className}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
